admin_question_index:
    path: /
    defaults:
        _controller: AdminBundle:Question:index

admin_question_list:
    path: /list
    defaults:
        _controller: AdminBundle:Question:list

admin_question_new:
    path: /new
    defaults:
        _controller: AdminBundle:Question:edit

admin_question_edit:
    path: /{id}/edit
    defaults:
        _controller: AdminBundle:Question:edit

admin_question_remove:
    path: /{id}/remove
    defaults:
        _controller: AdminBundle:Question:remove