admin_index:
    pattern:  /
    defaults: { _controller: AdminBundle:Default:index }

_admin_users:
    prefix: /user
    resource: @AdminBundle/Resources/config/routing/users.yml

_admin_category:
    prefix: /category
    resource: @AdminBundle/Resources/config/routing/category.yml

_admin_question:
    prefix: /question
    resource: @AdminBundle/Resources/config/routing/question.yml