logout:
    path: /logout

login_check:
    path: /login_check

login:
    path: /login
    defaults: { _controller: MainBundle:Security:login}

register:
    path: /register/
    defaults: {_controller: MainBundle:Security:register}

default:
    pattern:  /
    defaults: { _controller: MainBundle:Default:index }

_user:
    prefix: /user
    resource: routing/user.yml